export const SCREEN_WIDTH = 375;
export const SCREEN_HEIGHT = 677;
export const BALL_RADIUS = 15;
export const HOOP_WIDTH = 80;
export const HOOP_HEIGHT = 10;
export const HOOP_DEPTH = 70;
export const GRAVITY = 0.5;
export const FRICTION = 0.98;
export const BOUNCE = 0.7;
export const MIN_HOOP_DISTANCE = 60;
export const BOTTOM_HOOP_Y = 150; // Фиксированное расстояние нижней корзины от края
export const BOTTOM_HOOP_X = 80; // Фиксированное расстояние нижней корзины от края