export const SCREENS = {
    INTRO: 'INTRO',
    INTRO_REG: 'INTRO_REG',
    REG_1: 'REG_1',
    REG_2: 'REG_2',
    START: 'START',
    INTRO_RULES: 'INTRO_RULES',
    LOBBY: 'LOBBY',
    LOBBY1M: 'LOBBY1M',
    PLANNER1M: 'PLAN1M',
    FINISH: 'FINISH',
    PLUG: 'PLUG',
    GAME1M: 'GAME1M',
    GAME2M: 'GAME2M',
    BLENDER1M: 'BLENDER1M',
}

export const NEXT_SCREENS = {
    [SCREENS.INTRO_REG]: SCREENS.REG_1,
    [SCREENS.REG_1]: SCREENS.REG_2,
    [SCREENS.REG_2]: SCREENS.START,
    [SCREENS.START]: SCREENS.INTRO_RULES,
    [SCREENS.INTRO_RULES]: SCREENS.LOBBY1M,
}
